services:
  db:
    image: mysql:8.0
    container_name: abpc_db
    volumes:
      - abpc_db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress_network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: abpc_web
    volumes:
      - abpc_wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
    name: abpc_network
    internal: true

volumes:
  abpc_db_data: {}
  abpc_wordpress_data: {}
